### ISSUE TITLE
Suggestion: Change title color

### ISSUE THREAD

**Issue by salhadin48-git-collaborator** [Salhadin48-git/github-actions-crash-course#1]
I think it looks better if the main title is a bit more orange.

The style rule could be changed like this:

```css
h1 {
  color: #da9c31;
}
```
